### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by drsasa** [aminyazdanpanah/python-ffmpeg-video-streaming#19]
**Is your feature request related to a problem? Please describe.**
I'am looking for a way to add subtitle. Not sure is it possible. 

**Describe the solution you'd like**
When we add representations of video we want to be able to add
subtitle too.

**Comment by aminyazdanpanah** [comment]
It is not possible to add a subtitle to a stream because of segmented files(FFmpeg supports adding subtitles when it is a single file see http://ffmpeg.org/ffmpeg-filters.html#subtitles-1). But you can add subtitles in your HTML(or javascript) codes.

For example, if you are using Video.js to play streams, follow steps on the page below to add subtitles to your video.
https://docs.videojs.com/docs/guides/text-tracks.html

You can also use other players and add subtitles to your video(e.g Exoplayer on android).
Just Google it!
