### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by omid-fatehi** [aminyazdanpanah/python-ffmpeg-video-streaming#30]
Hello, I just implemented the code same as sample but get this error:

Request Method: | POST
-- | --
http://127.0.0.1:8000/videos/new/
3.0.4
FileNotFoundError
[WinError 2] The system cannot find the file specified

**Comment by aminyazdanpanah** [comment]
If you are using Windows, make sure you added FFmpeg and FFprobe binaries to your system path.

You can open a command prompt and run the following command:
``` bash
ffmpeg -version
```
If you did not get any error the path is fine, otherwise, you should add these binaries to your system path.
see the page below to learn how to do this:
https://www.wikihow.com/Install-FFmpeg-on-Windows

If you have any further problems, please post your code here.
